services:
  drumee:
    image: drumee/devel:latest
    container_name: perdrix
    ports:   
      - "53:53/udp"
      - "53:53/tcp"
      - "443:443/tcp"
      - "80:80/tcp"
      - "10000:10000/udp"
      - "5222:5222/tcp"

    # Below are environment variables for Drumee Container setup
    # Replace USERNAME with your own
    # Set your own private IP address
    environment:
      # Set your own private IP address. 
      # It's recommended to set a fixed IP address and disable DHCP for this host
      - "PRIVATE_IP4=0.0.0.0" 
      - PRIVATE_DOMAIN=local.drumee  # Default domain name  
      - DRUMEE_REPO=app.drumee.com # DO NOT CHANGE
      - INFRA_COMPONENTS=all # DO NOT CHANGE
      - DRUMEE_DESCRIPTION=My Drumee Development Server # Set yours
      - ADMIN_EMAIL=USERNAME@drumee.com # MANDATORY, set yours. 
      - ACME_EMAIL_ACCOUNT=USERNAME@drumee.com # default to ADMIN_EMAIL. Not need if only private domain
      - STORAGE_BACKUP="" # Optonal, format [user@backup.org:]/path/to/backup 
      - DB_BACKUP="" # Optonal, format [user@backup.org:]/path/to/backup 
      - INSTANCE_TYPE=devel

    volumes:
      # Change host volumes accordingly to you configs.
      # It's recommanded to have separated volumes
      # If possible, use good io perfomance for database volume 
      # DO NOT CHANGE right hand values
      - /var/lib/drumee/data/storage/db:/srv/db
      - /var/lib/drumee/data/storage/data:/data
      - /var/lib/drumee/data/storage/exchangearea:/exchangearea
      # This directory used to share your development files with the container
      # Change left hand value to your development directory
      # Example: /home/USERNAME/devel/perdrix
      # The path to this directory will be provided to setup perdrix server
      - /home/USERNAME/.config/perdrix:/mnt/devel
      # Comment the line below if you don't want to expose your home to within Docker
      # This is useful for development, but not recommended for production
      # If you want to use your home directory, change left hand value to your home directory
      # For security reasons, it is recommended to mount in read only
      - /home/USERNAME:/home/USERNAME:ro

    entrypoint: /var/lib/drumee/init.d/loader  # Comment this
    #entrypoint: /bin/bash                     # and uncomment this for debug or trouble shootiing
    stdin_open: true 
    tty: true 
    restart: unless-stopped
