
DELIMITER $
DROP FUNCTION IF EXISTS `skip_number`$
CREATE FUNCTION `skip_number`(
  _number INTEGER
)
RETURNS BOOLEAN DETERMINISTIC
BEGIN
  DECLARE _res BOOLEAN;
  SELECT _number LIKE "%666%" INTO _res;
  RETURN _res;
END$

DELIMITER ;
